### ISSUE TITLE
Support normal enums

### ISSUE THREAD

**Issue by vivianhellyer** [simd-lite/simd-json#141]
With #129, serde support for adjacent and internally tagged enums was added, but this left out... normal(?) enums.

I've written a minimal test case demonstrating a comparison between simd-json and serde_json. It deserialises a simple payload simply containing an enum and an object payload with a key value of an enum.

`Cargo.toml` (using the latest of each):
```toml
[dependencies]
serde = "=1.0.114"
serde_json = "=1.0.56"
simd-json = "=0.3.12"
```

`lib.rs`:
```rust
#[cfg(test)]
mod tests {
    use serde::Deserialize;

    #[derive(Deserialize)]
    pub struct Foo {
        #[allow(unused)]
        bar: Bar,
    }

    #[derive(Deserialize)]
    pub enum Bar {
        A,
    }

    #[test]
    fn object_simd_json() {
        let mut json = br#"{"bar":"A"}"#.to_vec();

        simd_json::from_slice::<Foo>(&mut json).unwrap();
    }

    #[test]
    fn simple_simd_json() {
        let mut json = br#""A""#.to_vec();

        simd_json::from_slice::<Bar>(&mut json).unwrap();
    }

    #[test]
    fn object_serde_json() {
        let mut json = br#"{"bar":"A"}"#.to_vec();

        serde_json::from_slice::<Foo>(&mut json).unwrap();
    }

    #[test]
    fn simple_serde_json() {
        let mut json = br#""A""#.to_vec();

        serde_json::from_slice::<Bar>(&mut json).unwrap();
    }
}
```

This results in:

```
running 4 tests
test tests::object_serde_json ... ok
test tests::object_simd_json ... FAILED
test tests::simple_serde_json ... ok
test tests::simple_simd_json ... FAILED

failures:

---- tests::object_simd_json stdout ----
thread 'tests::object_simd_json' panicked at 'called `Result::unwrap()` on an `Err` value: Error { index: 0, character: '💩', error: Serde("invalid type: string \"A\", expected enum Bar") }', src/lib.rs:20:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::simple_simd_json stdout ----
thread 'tests::simple_simd_json' panicked at 'called `Result::unwrap()` on an `Err` value: Error { index: 0, character: '💩', error: Serde("invalid type: string \"A\", expected enum Bar") }', src/lib.rs:27:9


failures:
    tests::object_simd_json
    tests::simple_simd_json
```

**Comment by Licenser** [comment]
Heya,
no there isn't much of a reason other than an oversight :). Will add it to the todo. Thanks for the test case that'll be super helpful!

**Comment by Licenser** [comment]
was super easy to fix :) released as 0.3.13

**Comment by vivianhellyer** [comment]
Looks like it fixes my use case, thanks!

(also, it looks like you left in a debug comment :) <https://github.com/simd-lite/simd-json/commit/1118c52549f53335e2cc65e4ebdae5a49a52b8a0#diff-e848cabe518211902a2d6ab8fbcec2dbR338>)

**Comment by Licenser** [comment]
oopsie!

**Comment by Licenser** [comment]
`v0.3.14`  w/o snot :D
