### ISSUE TITLE
Unchecked index out of bounds when parsing invalid JSON

### ISSUE THREAD

**Issue by 5225225** [simd-lite/simd-json#268]
The following code:

```rust
fn main() {
    let mut s: Vec<u8> = b"[100,9e999]".to_vec();
    simd_json::to_owned_value(&mut s);
}
```

panics in debug mode with

```rust
thread 'main' panicked at 'index out of bounds: the len is 5 but the index is 5', /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/safer_unchecked.rs:23:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_bounds_check
             at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/panicking.rs:159:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/slice/index.rs:260:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/slice/index.rs:18:9
   5: <[T] as simd_json::safer_unchecked::GetSaferUnchecked<T>>::get_kinda_unchecked
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/safer_unchecked.rs:23:14
   6: simd_json::numberparse::correct::f64_from_parts_slow
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/numberparse/correct.rs:361:30
   7: simd_json::numberparse::correct::f64_from_parts
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/numberparse/correct.rs:349:9
   8: simd_json::numberparse::correct::<impl simd_json::Deserializer>::parse_number
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/numberparse/correct.rs:155:13
   9: simd_json::stage2::<impl simd_json::Deserializer>::build_tape
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/stage2.rs:560:61
  10: simd_json::Deserializer::from_slice_with_buffers
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/lib.rs:505:13
  11: simd_json::Deserializer::from_slice_with_buffer
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/lib.rs:461:9
  12: simd_json::Deserializer::from_slice
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/lib.rs:441:9
  13: simd_json::value::owned::to_value
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.7.0/src/value/owned.rs:47:11
  14: scratchaYeJElpXm::main
             at ./src/main.rs:3:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/44cfafe2fafe816395d3acc434663a45d5178c41/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

(and it's UB in release mode without the checks)

This happens both with the published simd-json and the latest git checkout (https://github.com/simd-lite/simd-json/commit/11fd70df81fe720f5448234548cc584d9deb2484)

**Comment by Licenser** [comment]
Heya, thanks for reporting! 

I'll takle a look, it's probably a false positive / bad sizing for the fresh buffer as data is always relocated to a buffer that overhangs but but I'll double check :)

**Comment by Licenser** [comment]
I stan corrected. It's not a false positive. It was a bug in error reporting where the error tried to read the following character when there was nothing to follow. I'll fix this today.
