### ISSUE TITLE
panicked at pointer alignment check on nightly-2023-04-01

### ISSUE THREAD

**Issue by xxchan** [simd-lite/simd-json#272]
When we bump rust toolchain to latest nightly, we met a regression. After bisecting `rustc`, we found it's caused by newly added pointer alignment check https://github.com/rust-lang/rust/pull/98112 (available on `nightly-2023-04-01`

Not sure whether it's a bug. 👀 

https://github.com/simd-lite/simd-json/blob/525536aea66829c9ea0adea3665710488de81d1a/src/numberparse.rs#L68-L69

---

More context below:

```
panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7fda9c00f035', /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/numberparse.rs:69:29
--
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/std/src/panicking.rs:577:5
  | 1: core::panicking::panic_fmt
  | at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/panicking.rs:67:14
  | 2: core::panicking::panic_misaligned_pointer_dereference
  | at /rustc/28a29282f6dde2e4aba6e1e4cfea5c9430a00217/library/core/src/panicking.rs:174:5
  | 3: simd_json::numberparse::is_made_of_eight_digits_fast
  | at /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/numberparse.rs:69:29
  | 4: <simd_json::Deserializer>::parse_number
  | at /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/numberparse/correct.rs:85:20
  | 5: <simd_json::Deserializer>::build_tape
  | at /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/stage2.rs:454:61
  | 6: <simd_json::Deserializer>::from_slice_with_buffers
  | at /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/lib.rs:506:13
  | 7: <simd_json::Deserializer>::from_slice_with_buffer
  | at /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/lib.rs:462:9
  | 8: <simd_json::Deserializer>::from_slice
  | at /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/lib.rs:442:9
  | 9: simd_json::value::borrowed::to_value
  | at /risingwave/.cargo/git/checkouts/simd-json-0dd937541df12053/b52fef7/src/value/borrowed.rs:48:11
  | 10: <risingwave_connector::parser::json_parser::JsonParser>::parse_inner::{closure#0}
  | at ./src/parser/json_parser.rs:103:40

```
Our codebase:

https://github.com/risingwavelabs/risingwave/pull/9051

**Comment by Licenser** [comment]
https://github.com/simd-lite/simd-json/pull/271 is having a fix almost done :)
