### ISSUE TITLE
panicked at misaligned pointer dereference

### ISSUE THREAD

**Issue by xxchan** [simd-lite/simd-json#281]
not fixed in https://github.com/simd-lite/simd-json/pull/271
```rust
    let str = "9521.824380305317";
    let mut slice = str.as_bytes().to_owned();
    let value: simd_json::BorrowedValue<'_> = simd_json::to_borrowed_value(&mut slice).unwrap();
```

```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x144e06aa6', /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/numberparse.rs:115:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/core/src/panicking.rs:67:14
   2: core::panicking::panic_misaligned_pointer_dereference
             at /rustc/7f94b314cead7059a71a265a8b64905ef2511796/library/core/src/panicking.rs:174:5
   3: simd_json::numberparse::parse_eight_digits_unrolled
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/numberparse.rs:115:29
   4: simd_json::numberparse::correct::<impl simd_json::Deserializer>::parse_number
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/numberparse/correct.rs:90:25
   5: simd_json::stage2::<impl simd_json::Deserializer>::build_tape
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/stage2.rs:390:49
   6: simd_json::Deserializer::from_slice_with_buffers
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/lib.rs:506:13
   7: simd_json::Deserializer::from_slice_with_buffer
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/lib.rs:462:9
   8: simd_json::Deserializer::from_slice
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/lib.rs:442:9
   9: simd_json::value::borrowed::to_value
             at /Users/xxchan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.9.0/src/value/borrowed.rs:48:11
```

**Comment by Licenser** [comment]
Noooo! I'm sorry :(

**Comment by Licenser** [comment]
Okay so I can't reproduce this with nightly or stable rust, but I'm running a x86 system I suspect yours is a ARM?

**Comment by xxchan** [comment]
Yes I'm arm64 (Mac M1). I created a fix https://github.com/simd-lite/simd-json/pull/282. Don't know if it makes sense.

**Comment by Licenser** [comment]
You were faster :D but sadly the solution you have (I went down the same path so I learned it the hard way) conflicts with the x86 implementation of `parse_eight_digits_unrolled`.

What works well is using:
```rust
fn parse_eight_digits_unrolled(chars: &[u8]) -> u32 {
    let val = unsafe { (chars.as_ptr() as *const u64).read_unaligned() };
// ...
```

as that way the function signature remains the same.

If you want to update your PR with something like that (or any other solution that goes well in in x86 as well I'll gladly merge the contribution :)

**Comment by Licenser** [comment]
> I shouldn't try to fix it randomly :p

Nah, you put in the effort :) I appreciate that!

**Comment by Licenser** [comment]
released this fix as `v0.9.1`
