### ISSUE TITLE
Index out of bounds when parsing float in array

### ISSUE THREAD

**Issue by 5225225** [simd-lite/simd-json#311]
This is all I've managed to reduce it down to so far

```rust
fn main() {
    let mut data = "[11111111111111111111111111111E1,-111111111111111111111E111111111".to_string().into_bytes();

    simd_json::to_owned_value(&mut data);
}
```

This panics inside safer_unchecked, so this is unsafely indexing out of bounds. Tested this with SIMD and also allow-non-simd, both panics in the same place.

```rust
thread 'main' panicked at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/safer_unchecked.rs:23:18:
index out of bounds: the len is 32 but the index is 32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/35e416303e6591a71ef6a91e006c602d2def3968/library/std/src/panicking.rs:619:5
   1: core::panicking::panic_fmt
             at /rustc/35e416303e6591a71ef6a91e006c602d2def3968/library/core/src/panicking.rs:72:14
   2: core::panicking::panic_bounds_check
             at /rustc/35e416303e6591a71ef6a91e006c602d2def3968/library/core/src/panicking.rs:180:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/35e416303e6591a71ef6a91e006c602d2def3968/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/35e416303e6591a71ef6a91e006c602d2def3968/library/core/src/slice/index.rs:18:9
   5: <[T] as simd_json::safer_unchecked::GetSaferUnchecked<T>>::get_kinda_unchecked
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/safer_unchecked.rs:23:18
   6: simd_json::numberparse::correct::f64_from_parts_slow
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/numberparse/correct.rs:367:30
   7: simd_json::numberparse::correct::<impl simd_json::Deserializer>::parse_number
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/numberparse/correct.rs:152:28
   8: simd_json::stage2::<impl simd_json::Deserializer>::build_tape
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/stage2.rs:548:61
   9: simd_json::Deserializer::from_slice_with_buffers
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/lib.rs:511:13
  10: simd_json::Deserializer::from_slice_with_buffer
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/lib.rs:463:9
  11: simd_json::Deserializer::from_slice
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/lib.rs:443:9
  12: simd_json::value::owned::to_value
             at /home/jess/.cargo/registry/src/index.crates.io-6f17d22bba15001f/simd-json-0.10.6/src/value/owned.rs:48:11
  13: scratch::main
             at ./main.rs:4:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/35e416303e6591a71ef6a91e006c602d2def3968/library/core/src/ops/function.rs:250:5
```

**Comment by Licenser** [comment]
Thanks for finding this, fixed and released as `0.10.7`.
